[package]
name = "generic_optimization_framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.4"
dialoguer = "0.11.0"
rand = { version = "0.8.5", features = ["small_rng"] }
